# -*- cmake -*-
# - Find libbitcoin-system
# Find the libbitcoin-system includes and library
# This module defines
#  LIBBITCOINSYSTEMCPP_INCLUDE_DIRS, where to find libbitcoin-system.h, etc.
#  LIBBITCOINSYSTEMCPP_LIBRARIES, the libraries needed to use libbitcoin-system.
#  LIBBITCOINSYSTEMCPP_FOUND, If false, do not try to use libbitcoin-system.
#  also defined, but not for general use are
#  LIBBITCOINSYSTEMCPP_LIBRARIES, where to find the libbitcoin-system library.

FIND_PATH(LIBBITCOINSYSTEMCPP_INCLUDE_DIRS libbitcoin-system.h
/usr/include
/usr/local/include
${CMAKE_SOURCE_DIR}/win32-deps/include
PATH_SUFFIXES libbitcoin-system
)


FIND_LIBRARY(LIBBITCOINSYSTEMCPP_LIBRARIES NAMES libbitcoin-system HINTS /usr/lib /usr/local/lib 	${CMAKE_SOURCE_DIR}/win32-deps/lib)

IF (LIBBITCOINSYSTEMCPP_LIBRARIES AND LIBBITCOINSYSTEMCPP_INCLUDE_DIRS)
    SET(LIBBITCOINSYSTEMCPP_LIBRARIES ${LIBBITCOINSYSTEMCPP_LIBRARIES})
    SET(LIBBITCOINSYSTEMCPP_FOUND "YES")
ELSE (LIBBITCOINSYSTEMCPP_LIBRARIES AND LIBBITCOINSYSTEMCPP_INCLUDE_DIRS)
  SET(LIBBITCOINSYSTEMCPP_FOUND "NO")
ENDIF (LIBBITCOINSYSTEMCPP_LIBRARIES AND LIBBITCOINSYSTEMCPP_INCLUDE_DIRS)


IF (LIBBITCOINSYSTEMCPP_FOUND)
   IF (NOT LIBBITCOINSYSTEMCPP_FIND_QUIETLY)
      MESSAGE(STATUS "Found libbitcoin-system: ${LIBBITCOINSYSTEMCPP_LIBRARIES}")
   ENDIF (NOT LIBBITCOINSYSTEMCPP_FIND_QUIETLY)
ELSE (LIBBITCOINSYSTEMCPP_FOUND)
   IF (LIBBITCOINSYSTEMCPP_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find LIBBITCOINSYSTEMCPP library include: ${LIBBITCOINSYSTEMCPP_INCLUDE_DIRS}, lib: ${LIBBITCOINSYSTEMCPP_LIBRARIES}")
   ENDIF (LIBBITCOINSYSTEMCPP_FIND_REQUIRED)
ENDIF (LIBBITCOINSYSTEMCPP_FOUND)

# Deprecated declarations.
SET (NATIVE_LIBBITCOINSYSTEMCPP_INCLUDE_PATH ${LIBBITCOINSYSTEMCPP_INCLUDE_DIRS} )
GET_FILENAME_COMPONENT (NATIVE_LIBBITCOINSYSTEMCPP_LIB_PATH ${LIBBITCOINSYSTEMCPP_LIBRARIES} PATH)

MARK_AS_ADVANCED(
  LIBBITCOINSYSTEMCPP_LIBRARIES
  LIBBITCOINSYSTEMCPP_INCLUDE_DIRS
  )